# collections:
  # authors:
  #   output: true

defaults:
  # - scope:
  #     path: ""
  #     type: "authors"
  #   values:
  #     layout: "author"
  # - scope:
  #     path: ""
  #     type: "posts"
  #   values:
  #     layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# for SEO, etc.
title: Rob Keleher
description: I am a senior software and web developer with experience in frontend & full-stack development, project leadership and team leadership, with a passion about Japanese language, culture, and foreign exchange and 2 years of experience living and working in Japan as an English teacher.
url: http://www.robkeleher.com
author: Rob Keleher
logo: http://www.robkeleher.com/assets/images/cover.jpg
social:
  name: Rob Keleher
  links:
    - http://github.com/tryforceful
    - http://linkedin.com/in/robert-keleher

# for Jekyll theme
show_downloads: false
google_analytics:
theme: jekyll-theme-slate

bootstrap:
  assets: true

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-bootstrap-sass
  - jekyll-autoprefixer

# for build / serve
#source: .
#destination: ./_site
#includes_dir: _includes
exclude: ["deploy.sh", "unused", "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]

sass:
  style: compressed
  sass_dir: _sass
