collections:
  # authors:
  #   output: true

defaults:
  # - scope:
  #     path: ""
  #     type: "authors"
  #   values:
  #     layout: "author"
  # - scope:
  #     path: ""
  #     type: "posts"
  #   values:
  #     layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

title: Rob Keleher
show_downloads: false
google_analytics:
theme: jekyll-theme-slate

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag